# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/encrypted/system/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "rpool/encrypted/system/nix";
      fsType = "zfs";
    };

  fileSystems."/gnu" =
    { device = "rpool/encrypted/system/gnu";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "rpool/encrypted/system/var";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "rpool/encrypted/data/home";
      fsType = "zfs";
    };

  fileSystems."/var/cache" =
    { device = "rpool/encrypted/system/var/cache";
      fsType = "zfs";
    };

  fileSystems."/var/log" =
    { device = "rpool/encrypted/system/var/log";
      fsType = "zfs";
    };

  fileSystems."/home/games" =
    { device = "rpool/encrypted/data/games";
      fsType = "zfs";
    };

  fileSystems."/home/media" =
    { device = "rpool/encrypted/data/media";
      fsType = "zfs";
    };
  fileSystems."/home/jellyfin" = 
    { device = "rpool/encrypted/data/jellyfin";
      fsType = "zfs";
    };
  

  fileSystems."/home/projects" =
    { device = "rpool/encrypted/data/projects";
      fsType = "zfs";
    };

  fileSystems."/boot" = {
      device = "/dev/disk/by-partlabel/disk-sda-ESP";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
